markdown: kramdown
safe: false
exclude: ["vendor"]

permalink: /:categories/:title
relative_permalinks: false

## Uncomment and set your GitHub username to enable absolute links
github_user: stylobate

## Production URL (if different from default GitHub Pages one)
production_url: http://stylobate.github.io

## Comment out if (in absence of above fields) you'd like to use absolute `/` links
relative_urls_when_possible: true

link_handles:
    - prefix: "@"
      handle: "https://twitter.com/"
    - prefix: "gh:"
      handle: "https://github.com/"

## Unquote to set classes to quoted links instead of inline attributes
# quoted_link_wrapper_class: link link-wrapper
# quoted_link_inner_class: link-inner

menu:
    - concept
    - draft
    - kinds

## Localization
langs:
    - en
    - ru

default_lang: en

loc:
    laquo:
        ru: "«"
        en: "“"
    raquo:
        ru: "»"
        en: "”"
    stylobate:
        ru: "Стилобат"
        en: "Stylobate"

prose:
    rooturl: "pages"
    siteurl: "http://stylobate.github.io"
